server:
  port: 8010

spring:
  application:
    name: demo-gateway
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    trace-id128: true
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        root: /ms-demo
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8020/eureka/

zuul:
  routes:
    demo-app:
      path: /app/**
    demo-client:
      path: /client/**
    demo-service:
      path: /service/**