server:
  port: 8030

spring:
  application:
    name: demo-client
  zipkin:
    base-url: http://localhost:9000
  #  cloud:
  #    zookeeper:
  #      connect-string: localhost:2181
  #      discovery:
  #        register: true
  #        enabled: true
  #        root: /ifms


eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8020/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#app:
#  id: demo-client
#apollo:
#  cluster: shanghai
#  meta: http://127.0.0.1:8080


dubbo:
  application:
    name: dubbo-client
  protocol:
    name: dubbo
  #port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example.democlient