server:
  port: 8030

spring:
  application:
    name: demo-client
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
    trace-id128: true
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        root: /ms-demo

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#app:
#  id: demo-client
#apollo:
#  cluster: shanghai
#  meta: http://127.0.0.1:8080


dubbo:
  application:
    name: dubbo-client
  protocol:
    name: dubbo
  #port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example.democlient