server:
  port: 8021

eureka:
  instance:
    hostname: e1
  client:
    fetch-registry: false
    register-with-eureka: false
    enableSelfPreservation: false
    serviceUrl:
      defaultZone: http://e2:${server.port}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000